server:
  port: 8080

spring:
  application:
    name: mars-requrement

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        format_sql: false
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    generate-ddl: false
#    open-in-view: false
  datasource:
    ### [datasources]
    url: jdbc:postgresql://localhost:5431/postgres?currentSchema=mokb
    jdbc-url: jdbc:postgresql://localhost:5431/postgres?currentSchema=mokb
    username: postgres
    password: postgrs
    driverClassName: org.postgresql.Driver
  #    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      connection-timeout: 30000
#      pool-name: datasource-pool-${spring.application.name}
  liquibase:
    enabled: true
    change-log: classpath:ru.mokb.mars.database.liquibase.migrations/requrement.xml

saveFilePath: /home/andrew/foto/