server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: mars-requrement

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        format_sql: false
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    generate-ddl: false
#    open-in-view: false
  datasource:
    ### [datasources]
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=mokb}
    jdbc-url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=mokb}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:post}
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  #    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      connection-timeout: 30000
#      pool-name: datasource-pool-${spring.application.name}
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:ru.mokb.mars.database.liquibase.migrations/requrement.xml


saveFilePath: /home/andrew/foto/
templatePath: classpath:ru.mokb.mars.template/act.txt